In [2]:
import numpy as np
arr = np.array([2,4,5,67])
print(arr)

[ 2  4  5 67]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array([[2,4,5,67],[3,7,5,4]])
print(arr)

[[ 2  4  5 67]
 [ 3  7  5  4]]


In [3]:
import numpy as np
arr = np.array([2,4,5,67])
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(arr.dtype)
print(arr.astype(str))


[ 2  4  5 67]
(4,)
4
4
int64
['2' '4' '5' '67']


In [16]:
import numpy as np
arr = np.array([2,4,5,67])
aee = np.array([3,7,5,4])
print(arr+aee)
print(np.add(arr,aee))

[ 5 11 10 71]
[ 5 11 10 71]


In [21]:
import numpy as np
arr = np.array([2,4,5,67])
ae = np.array([3])
print(np.power(arr,ae))
print(np.square(arr))
print(np.sqrt(arr))

[     8     64    125 300763]
[   4   16   25 4489]
[1.41421356 2.         2.23606798 8.18535277]


In [20]:
import numpy as np
arr = np.array([2,4,5,67])
aee = np.array([3,7,5,4])
print(np.concatenate([arr,aee]))
print(np.vstack([arr,aee]))
print(np.array_split(arr,2))

[ 2  4  5 67  3  7  5  4]
[[ 2  4  5 67]
 [ 3  7  5  4]]
[array([2, 4]), array([ 5, 67])]


In [5]:
import numpy as np
arr = np.array([2,4,5,67])
print(arr[2])
print(np.append(arr,90))
print(np.append(arr,[40,30]))
print(np.insert(arr,1,50))

5
[ 2  4  5 67 90]
[ 2  4  5 67 40 30]
[ 2 50  4  5 67]


In [1]:
import numpy as np
arr = np.array([2,4,5,67])
print(np.delete(arr,2))

[ 2  4 67]


In [9]:
import numpy as np
arr = np.array([2,4,5,54,6,23])
print(np.sort(arr))
print(np.where(arr==5))
print(np.where(arr%2==0))

[ 2  4  5  6 23 54]
(array([2]),)
(array([0, 1, 3, 4]),)


In [11]:
import numpy as np
a = np.array([2,4,6,8,7])
fa = [True,False,True,False,False]
print(a[fa])

[2 6]


In [17]:
import numpy as np
arr = np.array([2,4,5,54,6,23])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr)/len(arr))
print(np.cumsum(arr)) 
print(np.cumprod(arr)) #multiply elements

94
2
54
15.666666666666666
[ 2  6 11 65 71 94]
[     2      8     40   2160  12960 298080]


In [33]:
# stactical fuction 
import numpy as np
import statistics as stas
arr = np.array([20,40,50,54,60,23,45,50]) 
print(np.mean(arr)) # avrage 
print(np.median(arr)) # first of all sort the iteam then find median value
print(stas.mode(arr)) # most frinquently number
print(np.std(arr))  # value spred means mean se value kitne kitne door pe hai
print(np.var(arr)) # square of standard deviation

42.75
47.5
50
13.460590625971804
181.1875


In [34]:
# coeficient and corrilation
sales = [100,200,500,450,300,250]
price = [20,15,10,18,20,17]
print(np.corrcoef([sales,price]))

[[ 1.         -0.57608791]
 [-0.57608791  1.        ]]
